# Generated by Django 2.2.6 on 2024-07-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=255, verbose_name='tweetid')),
                ('content', models.TextField(verbose_name='tweet内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '推特信息',
                'verbose_name_plural': '推特信息',
            },
        ),
    ]
